# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bef2e79ee3e17390ab30dd86a311ca828a2b5f9ef6496eb17f19a4e6bd7ec4bd7a1cecd8b73e95d14bdbc1016b38187185b8958b6b113f5c2b3bebb9da2ba866

test:
  secret_key_base: 0c1868b33587a00995d58bec9916151eda5ec5ce7fac7057c9a44c982b710edf3128ec0c30900260c4e803254c8470ddf0ebf47d49fee3f2bfe51ff6dc2db29b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
